keys:
  - &admin_m1cr0man age13lchgqu59yz7x2q6t7djev9k4m6pmh756wp59mdqueh382sqdeeq2rczzz
  - &server_gelandewagen age1zhe8pxej68p6ws98f8z6wc4rnf5nacve5v6xyc6juld7c6j773zqxufwg5
  - &server_unimog age1efge322n8kg4y3mu3lgefxdc99a0q22sd6n4plezw6gg0nentcfq40pwk4
  - &server_chuck age16pxktaeyt0py3tmrf423f5zmk8gx04rcv0cljuvzaw5k6ap96cusevwghc
  - &server_bgrs age1mzj3fhw43g5r9cduajqd8xcxth0zcrwetye5r4gf8v6u7la4v5fqmxxmcj
  - &server_optiplexxx age1ef6wy5vedl6x63gwjntwgjk6v95vrny78t4pw5uxl3dy6hndldtstjnsd8
  - &server_deic age10q255h9qmtgd53htlzvuauazz0qdkln6a0u0cjd50v02s6ezmp5qtadlam
creation_rules:
  - path_regex: modules/secrets/shared.yaml$
    key_groups:
    - age:
      - *admin_m1cr0man
      - *server_gelandewagen
      - *server_unimog
      - *server_chuck
      - *server_bgrs
      - *server_optiplexxx
      - *server_deic
  - path_regex: hosts/gelandewagen/secrets.yaml$
    key_groups:
    - age:
      - *admin_m1cr0man
      - *server_gelandewagen
  - path_regex: hosts/unimog/secrets.yaml$
    key_groups:
    - age:
      - *admin_m1cr0man
      - *server_unimog
  - path_regex: hosts/chuck/secrets.yaml$
    key_groups:
    - age:
      - *admin_m1cr0man
      - *server_chuck
  - path_regex: hosts/bgrs/secrets.yaml$
    key_groups:
    - age:
      - *admin_m1cr0man
      - *server_bgrs
  - path_regex: hosts/optiplexxx/secrets.yaml$
    key_groups:
    - age:
      - *admin_m1cr0man
      - *server_optiplexxx
  - path_regex: hosts/deic/secrets.yaml$
    key_groups:
    - age:
      - *admin_m1cr0man
      - *server_deic
  - path_regex: containers/.*/secrets.yaml$
    key_groups:
    - age:
      - *admin_m1cr0man
      - *server_unimog
  - path_regex: secrets.nix(.enc)?$
    key_groups:
    - age:
      - *admin_m1cr0man
