keys:
  - &admin_m1cr0man age13lchgqu59yz7x2q6t7djev9k4m6pmh756wp59mdqueh382sqdeeq2rczzz
  - &server_gelandewagen age1zhe8pxej68p6ws98f8z6wc4rnf5nacve5v6xyc6juld7c6j773zqxufwg5
creation_rules:
  - path_regex: modules/secrets/shared.yaml$
    key_groups:
    - age:
      - *admin_m1cr0man
      - *server_gelandewagen
  - path_regex: hosts/gelandewagen/secrets.yaml$
    key_groups:
    - age:
      - *admin_m1cr0man
      - *server_gelandewagen
  - path_regex: hosts/bgrs/secrets.yaml$
    key_groups:
    - age:
      - *admin_m1cr0man
      # TODO - *server_bgrs
