# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "usb_storage" "uas" "usbhid" "floppy" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ "i915" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  hardware.cpu.intel.updateMicrocode = config.hardware.enableRedistributableFirmware;

  fileSystems."/" =
    { device = "zroot/nixos";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-partuuid/a327d6c3-c5da-4bfd-8696-fc021dfbc325";
      fsType = "ext3";
    };

  fileSystems."/nix" =
    { device = "zroot/nix_store";
      fsType = "zfs";
    };

  # Make sure nix_store has acltype=off to make sure this works.
  # TODO in the event of a reload, set dedup=skein,checksum=skein,zstd_compress=zstd
  fileSystems."/exports/netboot/nix_store" =
    { device = "zroot/nix_store@netboot";
      fsType = "zfs";
      options = [ "ro" "nofail" "noacl" ];
    };

  fileSystems."/home" =
    { device = "zroot/home";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/exports/games" =
    { device = "zroot/games";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  swapDevices =[
    { device = "/dev/disk/by-partuuid/acbee226-0160-4e2d-8bcb-64faf83770a8"; }
  ];
}
