# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "zsarah/nixos/root";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-partuuid/5f49f8ef-06e6-4e38-a534-dfaeed505102";
      fsType = "vfat";
    };

  fileSystems."/nix" =
    { device = "zsarah/nixos/nix";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "zsarah/home";
      fsType = "zfs";
    };

  fileSystems."/var" =
    { device = "zsarah/nixos/var";
      fsType = "zfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-partuuid/dde342a2-f828-4e6e-9acb-b7afd32821ae"; }
    ];

  virtualisation.hypervGuest.enable = true;
}
