# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

let
  mountConfig = name: {
    device = "zroot/${name}";
    fsType = "zfs";
    options = [ "nofail" ];
  };
in {
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "usb_storage" "sd_mod" "r8169" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "zroot/nixos";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "zroot/nixos/nix";
      fsType = "zfs";
    };

  fileSystems."/zroot/backup_restore" = mountConfig "backup_restore";

  fileSystems."/zroot/adam_mc" = mountConfig "adam_mc";

  fileSystems."/zroot/craig_mc" = mountConfig "craig_mc";

  fileSystems."/zroot/rhiannon_mc" = mountConfig "rhiannon_mc";

  fileSystems."/zroot/modded_mc" = mountConfig "modded_mc";

  fileSystems."/var/lib/docker" = mountConfig "docker";

  fileSystems."/var/lib/generic" = mountConfig "generic";

  fileSystems."/zroot/minio" = mountConfig "minio";

  fileSystems."/zroot/steamapps" = mountConfig "steamapps";

  fileSystems."/zroot/tick" = mountConfig "tick";

  fileSystems."/zroot/vms" = mountConfig "vms";

  fileSystems."/zroot/m1cr0blog" = mountConfig "m1cr0blog";

  swapDevices = [
    { device = "/dev/disk/by-uuid/3fb7701e-18a8-4a64-b183-29431615525c"; }
  ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
